---
- name: Converge
  hosts: all
  roles:
    - role: ansible-springboot-demo
      vars:
        install_java: true
        java_package: 'java-1.8.0-openjdk-1.8.0.181'
        application_name: hellospring
        application_url: https://github.com/vbrednikov/springboot-demo-app/releases/download/v0.1.0/hellospring-0.1.0.jar
        application_sha: "sha256:ad4a297ab3fad45d166ca0b8608050119820c3547d6f92fd4afa48f543efc0e6"
        listen_port: 8090
