---
- name: Prepare
  hosts: all
  tasks:
  - name: install initscripts
    package:
      name: initscripts
      state: present
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == "6"
  - name: install ss
    package:
      name: iproute
      state: present
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == "7"
